### ISSUE TITLE
Undefined or value 0

### ISSUE THREAD

**Issue by henryruhs** [jsoverson/grunt-strip#1]
Empty files are causing an undefined inside the every file.

I also get the value 0 to successful once your script striped out the match.

**Comment by jsoverson** [comment]
I'll look into the empty file issue, can you elaborate on the other issue?

**Comment by henryruhs** [comment]
var foo = 'foo';

console.log('foo');

results:

var foo = 'foo';

0;

ps: I'm not using the grunt devs and my setup is:

```
    strip:
    {
        scripts:
        {
            files: ['<config:lint.base>', '<config:lint.modules>', '<config:lint.templates>'],
            inline: true,
            nodes : ['console']
        }
    },
```

**Comment by jsoverson** [comment]
I'm i'm understanding you correctly, that is the expected behavior. The plugin replaces nodes with a falsey but still existant statement. In this case `0` fits the bill the best. This is to prevent concerns with situations like

```
if (something) console.log("Foo")
doThis()
```

If console.log was replaced with an empty string, `doThis()` would execute instead, changing the flow. Replacing nodes with a 0 alleviates this problem.

**Comment by henryruhs** [comment]
This would not happen if you using {} :-D ...

You should tell inside your docs the expected behavior. For me this looks like an error.

Btw: removing var_dump() from PHP files would be nice too, just an idea...

**Comment by jsoverson** [comment]
It's outlined in the doc, but I will update the readme to make this more obvious

https://github.com/jsoverson/grunt-strip#how-its-done

Thanks for the notice on the other issue.

**Comment by henryruhs** [comment]
You are welcome :-)
